### ISSUE TITLE
Create CocoaPod

### ISSUE THREAD

**Issue by bgiori** [JuulLabs-OSS/mcumgr-ios#12]
We should have a CocoaPod available too

**Comment by tristandl** [comment]
this looks like it's created now?

**Comment by bgiori** [comment]
There is a branch which has built v0.6.2 for cocoapods which an be used at the moment. However, I remove Carthage support in that branch so there is still work to do to have both working. that is why the branch is still not yet merged into master and this ticket is still open.

**Comment by tristandl** [comment]
ok sure thing, but i can see the podspec in master, and can install McuManager via pods - which is why i thought it was merged? i can't see a branch for cocoapods (merged or open). happy to help if i can 👍

**Comment by bgiori** [comment]
Ah, yes I added the podspec into master, but realized that more needed to be done (so I branched). The branch is called `cbor-as-dependency`.
