### ISSUE TITLE
Bluetooth transport may be broken on iOS 13

### ISSUE THREAD

**Issue by philips77** [JuulLabs-OSS/mcumgr-ios#25]
Hi,
On iOS 13 it is now required to wait until the `CBCentralManager` is in `.poweredOn` state before calling `retrievePeripherals(withIdentifier:)`. Have a look at this line: https://github.com/JuulLabs-OSS/mcumgr-ios/blob/13ba851af50d8ca5fdcd89e5b592723b30a857ed/Source/Bluetooth/McuMgrBleTransport.swift#L116-L117

In DFU Library for iOS we had similar issue, which has been fixed with this commit: https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/commit/a64315b516f5c9c8bb52451b4b277e79a1ec9640
Retrieving peripheral was delayed until the manager was ready. Similar fix should be applied in MCUMGR library.

**Comment by bgiori** [comment]
Hey Aleksander, 
Thanks for the heads up, I should be able to get to this sometime shortly.

**Comment by amorde** [comment]
I've seen this as well, prevents DFU from working at all on iOS 13. Throwing in a +1 :)
