### ISSUE TITLE
LogEntry init bug results in empty messages

### ISSUE THREAD

**Issue by lm2s** [JuulLabs-OSS/mcumgr-ios#30]
Incorrect initializer in `LogEntry` results in empty log entry message.
Tries to cast `cbor?["msg"]` as `CBOR.byteString`, but it fails because `cbor?["msg"]` is of type `utf8String`. 

`if case let CBOR.byteString(msg)? = cbor?["msg"] {self.msg = msg}` _(McuMgrResponse.swift:524)_

Debugger output:
```
(lldb) p cbor?["msg"]
(SwiftCBOR.CBOR?) $R0 = utf8String {
  utf8String = "rsn:SOFT, cnt:1, img:0.0.8.3, hash:ac50b09683a5bbbed0429b02dc8b4e0aee4e0bf5282edc9aa0ca50bcca479f4d"
}
```

As such `LogEntry.msg` stays `nil`.

To fix this, `LogEntry.msg` should be of type `CBOR` and the casting should be performed on the `getMessage()` method, which already has partially the necessary logic to do so and just needs minor adjustments.

I'll submit a PR with a fix.

**Comment by bgiori** [comment]
https://github.com/JuulLabs-OSS/mcumgr-android/issues/58

It seems you're firmware log version is old. This library only supports `LOG_VERSION=3`

**Comment by lm2s** [comment]
Yes, this was the issue. Thank you :)
