### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by philips77** [JuulLabs-OSS/mcumgr-ios#49]
Hello,
Any reason why this isn't available through Swift Package Manager?

**Comment by bgiori** [comment]
Hey, no reason other than I have not done any iOS work in a while. 

Not up to date with the current package management solutions.

**Comment by bgiori** [comment]
Thanks @florianbuerger!

Support for SPM has been released with 0.12.0

**Comment by ramunasjurgilas** [comment]
Unfortunately it integration throw SPM failing.
https://github.com/JuulLabs-OSS/mcumgr-ios/issues/56
