### ISSUE TITLE
SPM integration fails: Dependencies could not be resolved because root depends on 'mcumgr-ios' 0.12.0..<1.0.0

### ISSUE THREAD

**Issue by ramunasjurgilas** [JuulLabs-OSS/mcumgr-ios#56]
When adding mcumgr-ios it fails with error:

> Dependencies could not be resolved because root depends on 'mcumgr-ios' 0.12.0..<1.0.0.
> 'mcumgr-ios' >= 0.12.0 cannot be used because no versions of 'mcumgr-ios' match the requirement 0.12.1..<1.0.0 and package 'mcumgr-ios' is required using a stable-version but 'mcumgr-ios' depends on an unstable-version package 'swiftcbor'.

![image](https://user-images.githubusercontent.com/255732/119345288-59f64380-bca1-11eb-84d8-43584518f0a9.png)

**Comment by florianbuerger** [comment]
As a workaround, you should be able to add it by specifying the `master` branch. Seems https://github.com/unrelentingtech/SwiftCBOR/releases is missing a couple of tagged releases.
![ScreenShot 2021-06-25 at 11 44 26](https://user-images.githubusercontent.com/119219/123406090-d5058f00-d5aa-11eb-8d25-9b327672445d.png)

**Comment by ramunasjurgilas** [comment]
@florianbuerger Thanks for quick fix. ;)
